%extracting images
imgSets = [imageSet('/home/cse/101_ObjectCategories/accordion'),...
imageSet('/home/cse/101_ObjectCategories/airplanes'),...
imageSet('/home/cse/101_ObjectCategories/anchor'),...
imageSet('/home/cse/101_ObjectCategories/ant'),...
imageSet('/home/cse/101_ObjectCategories/BACKGROUND_Google'),...
imageSet('/home/cse/101_ObjectCategories/barrel'),...
imageSet('/home/cse/101_ObjectCategories/bass'),...
imageSet('/home/cse/101_ObjectCategories/beaver'),...
imageSet('/home/cse/101_ObjectCategories/binocular'),...
imageSet('/home/cse/101_ObjectCategories/bonsai'),...
imageSet('/home/cse/101_ObjectCategories/brain'),...
imageSet('/home/cse/101_ObjectCategories/brontosaurus'),...
imageSet('/home/cse/101_ObjectCategories/buddha'),...
imageSet('/home/cse/101_ObjectCategories/butterfly'),...
imageSet('/home/cse/101_ObjectCategories/camera'),...
imageSet('/home/cse/101_ObjectCategories/cannon'),...
imageSet('/home/cse/101_ObjectCategories/car_side'),...
imageSet('/home/cse/101_ObjectCategories/ceiling_fan'),...
imageSet('/home/cse/101_ObjectCategories/cellphone'),...
imageSet('/home/cse/101_ObjectCategories/chair'),...
imageSet('/home/cse/101_ObjectCategories/chandelier'),...
imageSet('/home/cse/101_ObjectCategories/cougar_body'),...
imageSet('/home/cse/101_ObjectCategories/cougar_face'),...
imageSet('/home/cse/101_ObjectCategories/crab'),...
imageSet('/home/cse/101_ObjectCategories/crayfish'),...
imageSet('/home/cse/101_ObjectCategories/crocodile'),...
imageSet('/home/cse/101_ObjectCategories/crocodile_head'),...
imageSet('/home/cse/101_ObjectCategories/cup'),...
imageSet('/home/cse/101_ObjectCategories/dalmatian'),...
imageSet('/home/cse/101_ObjectCategories/dollar_bill'),...
imageSet('/home/cse/101_ObjectCategories/dolphin'),...
imageSet('/home/cse/101_ObjectCategories/dragonfly'),...
imageSet('/home/cse/101_ObjectCategories/electric_guitar'),...
imageSet('/home/cse/101_ObjectCategories/elephant'),...
imageSet('/home/cse/101_ObjectCategories/emu'),...
imageSet('/home/cse/101_ObjectCategories/euphonium'),...
imageSet('/home/cse/101_ObjectCategories/ewer'),...
imageSet('/home/cse/101_ObjectCategories/Faces'),...
imageSet('/home/cse/101_ObjectCategories/Faces_easy'),...
imageSet('/home/cse/101_ObjectCategories/ferry'),...
imageSet('/home/cse/101_ObjectCategories/flamingo'),...
imageSet('/home/cse/101_ObjectCategories/flamingo_head'),...
imageSet('/home/cse/101_ObjectCategories/garfield'),...
imageSet('/home/cse/101_ObjectCategories/gerenuk'),...
imageSet('/home/cse/101_ObjectCategories/gramophone'),...
imageSet('/home/cse/101_ObjectCategories/grand_piano'),...
imageSet('/home/cse/101_ObjectCategories/hawksbill'),...
imageSet('/home/cse/101_ObjectCategories/headphone'),...
imageSet('/home/cse/101_ObjectCategories/hedgehog'),...
imageSet('/home/cse/101_ObjectCategories/helicopter'),...
imageSet('/home/cse/101_ObjectCategories/ibis'),...
imageSet('/home/cse/101_ObjectCategories/inline_skate'),...
imageSet('/home/cse/101_ObjectCategories/joshua_tree'),...
imageSet('/home/cse/101_ObjectCategories/kangaroo'),...
imageSet('/home/cse/101_ObjectCategories/ketch'),...
imageSet('/home/cse/101_ObjectCategories/lamp'),...
imageSet('/home/cse/101_ObjectCategories/laptop'),...
imageSet('/home/cse/101_ObjectCategories/Leopards'),...
imageSet('/home/cse/101_ObjectCategories/llama'),...
imageSet('/home/cse/101_ObjectCategories/lobster'),...
imageSet('/home/cse/101_ObjectCategories/lotus'),...
imageSet('/home/cse/101_ObjectCategories/mandolin'),...
imageSet('/home/cse/101_ObjectCategories/mayfly'),...
imageSet('/home/cse/101_ObjectCategories/menorah'),...
imageSet('/home/cse/101_ObjectCategories/metronome'),...
imageSet('/home/cse/101_ObjectCategories/minaret'),...
imageSet('/home/cse/101_ObjectCategories/Motorbikes'),...
imageSet('/home/cse/101_ObjectCategories/nautilus'),...
imageSet('/home/cse/101_ObjectCategories/octopus'),...
imageSet('/home/cse/101_ObjectCategories/okapi'),...
imageSet('/home/cse/101_ObjectCategories/pagoda'),...
imageSet('/home/cse/101_ObjectCategories/panda'),...
imageSet('/home/cse/101_ObjectCategories/pigeon'),...
imageSet('/home/cse/101_ObjectCategories/pizza'),...
imageSet('/home/cse/101_ObjectCategories/platypus'),...
imageSet('/home/cse/101_ObjectCategories/pyramid'),...
imageSet('/home/cse/101_ObjectCategories/revolver'),...
imageSet('/home/cse/101_ObjectCategories/rhino'),...
imageSet('/home/cse/101_ObjectCategories/rooster'),...
imageSet('/home/cse/101_ObjectCategories/saxophone'),...
imageSet('/home/cse/101_ObjectCategories/schooner'),...
imageSet('/home/cse/101_ObjectCategories/scissors'),...
imageSet('/home/cse/101_ObjectCategories/scorpion'),...
imageSet('/home/cse/101_ObjectCategories/sea_horse'),...
imageSet('/home/cse/101_ObjectCategories/snoopy'),...
imageSet('/home/cse/101_ObjectCategories/soccer_ball'),...
imageSet('/home/cse/101_ObjectCategories/stapler'),...
imageSet('/home/cse/101_ObjectCategories/starfish'),...
imageSet('/home/cse/101_ObjectCategories/stegosaurus'),...
imageSet('/home/cse/101_ObjectCategories/stop_sign'),...
imageSet('/home/cse/101_ObjectCategories/strawberry'),...
imageSet('/home/cse/101_ObjectCategories/sunflower'),...
imageSet('/home/cse/101_ObjectCategories/tick'),...
imageSet('/home/cse/101_ObjectCategories/trilobite'),...
imageSet('/home/cse/101_ObjectCategories/umbrella'),...
imageSet('/home/cse/101_ObjectCategories/watch'),...
imageSet('/home/cse/101_ObjectCategories/water_lilly'),...
imageSet('/home/cse/101_ObjectCategories/wheelchair'),...
imageSet('/home/cse/101_ObjectCategories/wild_cat'),...
imageSet('/home/cse/101_ObjectCategories/windsor_chair'),...
imageSet('/home/cse/101_ObjectCategories/wrench'),...
imageSet('/home/cse/101_ObjectCategories/yin_yang')];
{ imgSets.Description } % display all labels on one line
[imgSets.Count]         % show the corresponding count of images
minSetCount = min([imgSets.Count]); % determine the smallest amount of images in a category

% Use partition method to trim the set.
imgSets = partition(imgSets, 20, 'randomize');

% Notice that each set now has exactly the same number of images.
[imgSets.Count]
[trainingSets, validationSets] = partition(imgSets, 0.7, 'randomize');
bag = bagOfFeatures(trainingSets);

%SVM parameters and kernel setting
opts1 = templateSVM('BoxConstraint', 1, 'KernelFunction', 'gaussian');
categoryClassifier1 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts1);
confMatrix1 = evaluate(categoryClassifier1, validationSets);

opts2 = templateSVM('BoxConstraint', 2, 'KernelFunction', 'gaussian');
categoryClassifier2 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts2);
confMatrix2 = evaluate(categoryClassifier2, validationSets);

opts3 = templateSVM('BoxConstraint', 3, 'KernelFunction', 'gaussian');
categoryClassifier3 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts3);
confMatrix3 = evaluate(categoryClassifier3, validationSets);

opts4 = templateSVM('BoxConstraint', 4, 'KernelFunction','gaussian');
categoryClassifier4 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts4);
confMatrix4 = evaluate(categoryClassifier4, validationSets);

opts5 = templateSVM('BoxConstraint', 5, 'KernelFunction', 'gaussian');
categoryClassifier5 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts5);
confMatrix5 = evaluate(categoryClassifier5, validationSets);

opts6 = templateSVM('BoxConstraint', 0.6, 'KernelFunction', 'gaussian');
categoryClassifier6 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts6);
confMatrix6 = evaluate(categoryClassifier6, validationSets);

opts7 = templateSVM('BoxConstraint', 0.1, 'KernelFunction', 'gaussian');
categoryClassifier7 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts7);
confMatrix7 = evaluate(categoryClassifier7, validationSets);

opts8 = templateSVM('BoxConstraint', 10, 'KernelFunction', 'gaussian');
categoryClassifier8 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts8);
confMatrix8 = evaluate(categoryClassifier8, validationSets);

opts9 = templateSVM('BoxConstraint', 15, 'KernelFunction', 'gaussian');
categoryClassifier9 = trainImageCategoryClassifier(trainingSets, bag, 'LearnerOptions', opts9);
confMatrix9 = evaluate(categoryClassifier9, validationSets);

% Compute average accuracy
mean(diag(confMatrix1))
mean(diag(confMatrix2))
mean(diag(confMatrix3))
mean(diag(confMatrix4))
mean(diag(confMatrix5))
mean(diag(confMatrix6))
mean(diag(confMatrix7))
mean(diag(confMatrix8))
mean(diag(confMatrix9))