imgSets = [imageSet('/home/rahul/Downloads/101_ObjectCategories/accordion'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/airplanes'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/anchor'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/ant'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/BACKGROUND_Google'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/barrel'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/bass'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/beaver'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/binocular'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/bonsai'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/brain'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/brontosaurus'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/buddha'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/butterfly'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/camera'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/cannon'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/car_side'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/ceiling_fan'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/cellphone'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/chair'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/chandelier'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/cougar_body'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/cougar_face'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/crab'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/crayfish'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/crocodile'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/crocodile_head'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/cup'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/dalmatian'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/dollar_bill'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/dolphin'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/dragonfly'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/electric_guitar'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/elephant'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/emu'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/euphonium'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/ewer'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/Faces'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/Faces_easy'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/ferry'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/flamingo'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/flamingo_head'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/garfield'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/gerenuk'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/gramophone'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/grand_piano'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/hawksbill'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/headphone'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/hedgehog'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/helicopter'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/ibis'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/inline_skate'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/joshua_tree'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/kangaroo'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/ketch'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/lamp'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/laptop'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/Leopards'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/llama'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/lobster'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/lotus'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/mandolin'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/mayfly'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/menorah'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/metronome'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/minaret'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/Motorbikes'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/nautilus'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/octopus'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/okapi'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/pagoda'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/panda'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/pigeon'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/pizza'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/platypus'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/pyramid'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/revolver'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/rhino'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/rooster'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/saxophone'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/schooner'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/scissors'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/scorpion'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/sea_horse'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/snoopy'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/soccer_ball'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/stapler'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/starfish'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/stegosaurus'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/stop_sign'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/strawberry'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/sunflower'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/tick'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/trilobite'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/umbrella'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/watch'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/water_lilly'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/wheelchair'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/wild_cat'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/windsor_chair'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/wrench'),...
imageSet('/home/rahul/Downloads/101_ObjectCategories/yin_yang')];
{ imgSets.Description } % display all labels on one line
[imgSets.Count]         % show the corresponding count of images
minSetCount = min([imgSets.Count]); % determine the smallest amount of images in a category

% Use partition method to trim the set.
imgSets = partition(imgSets, 30, 'randomize');

% Notice that each set now has exactly the same number of images.
[imgSets.Count]
[trainingSets, validationSets] = partition(imgSets, 0.3, 'randomize');
bag = bagOfFeatures(trainingSets);
opts = templateSVM('BoxConstraint', 1.1, 'KernelFunction', 'gaussian');
categoryClassifier = trainImageCategoryClassifier(imgSets, bag, 'LearnerOptions', opts);
confMatrix = evaluate(categoryClassifier, validationSets)

% Compute average accuracy
mean(diag(confMatrix))