imgSets = [imageSet('/home/cse/101_ObjectCategories/accordion'),...
imageSet('/home/cse/101_ObjectCategories/airplanes'),...
imageSet('/home/cse/101_ObjectCategories/anchor'),...
imageSet('/home/cse/101_ObjectCategories/ant'),...
imageSet('/home/cse/101_ObjectCategories/BACKGROUND_Google'),...
imageSet('/home/cse/101_ObjectCategories/barrel'),...
imageSet('/home/cse/101_ObjectCategories/bass'),...
imageSet('/home/cse/101_ObjectCategories/beaver'),...
imageSet('/home/cse/101_ObjectCategories/binocular'),...
imageSet('/home/cse/101_ObjectCategories/bonsai'),...
imageSet('/home/cse/101_ObjectCategories/brain'),...
imageSet('/home/cse/101_ObjectCategories/brontosaurus'),...
imageSet('/home/cse/101_ObjectCategories/buddha'),...
imageSet('/home/cse/101_ObjectCategories/butterfly'),...
imageSet('/home/cse/101_ObjectCategories/camera'),...
imageSet('/home/cse/101_ObjectCategories/cannon'),...
imageSet('/home/cse/101_ObjectCategories/car_side'),...
imageSet('/home/cse/101_ObjectCategories/ceiling_fan'),...
imageSet('/home/cse/101_ObjectCategories/cellphone'),...
imageSet('/home/cse/101_ObjectCategories/chair'),...
imageSet('/home/cse/101_ObjectCategories/chandelier'),...
imageSet('/home/cse/101_ObjectCategories/cougar_body'),...
imageSet('/home/cse/101_ObjectCategories/cougar_face'),...
imageSet('/home/cse/101_ObjectCategories/crab'),...
imageSet('/home/cse/101_ObjectCategories/crayfish'),...
imageSet('/home/cse/101_ObjectCategories/crocodile'),...
imageSet('/home/cse/101_ObjectCategories/crocodile_head'),...
imageSet('/home/cse/101_ObjectCategories/cup'),...
imageSet('/home/cse/101_ObjectCategories/dalmatian'),...
imageSet('/home/cse/101_ObjectCategories/dollar_bill'),...
imageSet('/home/cse/101_ObjectCategories/dolphin'),...
imageSet('/home/cse/101_ObjectCategories/dragonfly'),...
imageSet('/home/cse/101_ObjectCategories/electric_guitar'),...
imageSet('/home/cse/101_ObjectCategories/elephant'),...
imageSet('/home/cse/101_ObjectCategories/emu'),...
imageSet('/home/cse/101_ObjectCategories/euphonium'),...
imageSet('/home/cse/101_ObjectCategories/ewer'),...
imageSet('/home/cse/101_ObjectCategories/Faces'),...
imageSet('/home/cse/101_ObjectCategories/Faces_easy'),...
imageSet('/home/cse/101_ObjectCategories/ferry'),...
imageSet('/home/cse/101_ObjectCategories/flamingo'),...
imageSet('/home/cse/101_ObjectCategories/flamingo_head'),...
imageSet('/home/cse/101_ObjectCategories/garfield'),...
imageSet('/home/cse/101_ObjectCategories/gerenuk'),...
imageSet('/home/cse/101_ObjectCategories/gramophone'),...
imageSet('/home/cse/101_ObjectCategories/grand_piano'),...
imageSet('/home/cse/101_ObjectCategories/hawksbill'),...
imageSet('/home/cse/101_ObjectCategories/headphone'),...
imageSet('/home/cse/101_ObjectCategories/hedgehog'),...
imageSet('/home/cse/101_ObjectCategories/helicopter'),...
imageSet('/home/cse/101_ObjectCategories/ibis'),...
imageSet('/home/cse/101_ObjectCategories/inline_skate'),...
imageSet('/home/cse/101_ObjectCategories/joshua_tree'),...
imageSet('/home/cse/101_ObjectCategories/kangaroo'),...
imageSet('/home/cse/101_ObjectCategories/ketch'),...
imageSet('/home/cse/101_ObjectCategories/lamp'),...
imageSet('/home/cse/101_ObjectCategories/laptop'),...
imageSet('/home/cse/101_ObjectCategories/Leopards'),...
imageSet('/home/cse/101_ObjectCategories/llama'),...
imageSet('/home/cse/101_ObjectCategories/lobster'),...
imageSet('/home/cse/101_ObjectCategories/lotus'),...
imageSet('/home/cse/101_ObjectCategories/mandolin'),...
imageSet('/home/cse/101_ObjectCategories/mayfly'),...
imageSet('/home/cse/101_ObjectCategories/menorah'),...
imageSet('/home/cse/101_ObjectCategories/metronome'),...
imageSet('/home/cse/101_ObjectCategories/minaret'),...
imageSet('/home/cse/101_ObjectCategories/Motorbikes'),...
imageSet('/home/cse/101_ObjectCategories/nautilus'),...
imageSet('/home/cse/101_ObjectCategories/octopus'),...
imageSet('/home/cse/101_ObjectCategories/okapi'),...
imageSet('/home/cse/101_ObjectCategories/pagoda'),...
imageSet('/home/cse/101_ObjectCategories/panda'),...
imageSet('/home/cse/101_ObjectCategories/pigeon'),...
imageSet('/home/cse/101_ObjectCategories/pizza'),...
imageSet('/home/cse/101_ObjectCategories/platypus'),...
imageSet('/home/cse/101_ObjectCategories/pyramid'),...
imageSet('/home/cse/101_ObjectCategories/revolver'),...
imageSet('/home/cse/101_ObjectCategories/rhino'),...
imageSet('/home/cse/101_ObjectCategories/rooster'),...
imageSet('/home/cse/101_ObjectCategories/saxophone'),...
imageSet('/home/cse/101_ObjectCategories/schooner'),...
imageSet('/home/cse/101_ObjectCategories/scissors'),...
imageSet('/home/cse/101_ObjectCategories/scorpion'),...
imageSet('/home/cse/101_ObjectCategories/sea_horse'),...
imageSet('/home/cse/101_ObjectCategories/snoopy'),...
imageSet('/home/cse/101_ObjectCategories/soccer_ball'),...
imageSet('/home/cse/101_ObjectCategories/stapler'),...
imageSet('/home/cse/101_ObjectCategories/starfish'),...
imageSet('/home/cse/101_ObjectCategories/stegosaurus'),...
imageSet('/home/cse/101_ObjectCategories/stop_sign'),...
imageSet('/home/cse/101_ObjectCategories/strawberry'),...
imageSet('/home/cse/101_ObjectCategories/sunflower'),...
imageSet('/home/cse/101_ObjectCategories/tick'),...
imageSet('/home/cse/101_ObjectCategories/trilobite'),...
imageSet('/home/cse/101_ObjectCategories/umbrella'),...
imageSet('/home/cse/101_ObjectCategories/watch'),...
imageSet('/home/cse/101_ObjectCategories/water_lilly'),...
imageSet('/home/cse/101_ObjectCategories/wheelchair'),...
imageSet('/home/cse/101_ObjectCategories/wild_cat'),...
imageSet('/home/cse/101_ObjectCategories/windsor_chair'),...
imageSet('/home/cse/101_ObjectCategories/wrench'),...
imageSet('/home/cse/101_ObjectCategories/yin_yang')];
{ imgSets.Description } % display all labels on one line
[imgSets.Count]         % show the corresponding count of images
minSetCount = min([imgSets.Count]); % determine the smallest amount of images in a category

% Use partition method to trim the set.
%imgSets = partition(imgSets, minSetCount, 'randomize');

% Notice that each set now has exactly the same number of images.
[imgSets.Count]

run('vlfeat/toolbox/vl_setup')

y = []
for i = 1:102
   i
   for j = 1:imgSets(i).Count;
        I_img.label = i ;
        I = read(imgSets(i),j);
        if size(I,3) == 3
            I = rgb2gray(I);
        end
        I = single(I) ;
        [f,d] = vl_sift(I) ;
        I_img.descrip = single(d);
        if exist('X','var')
            X = [X d];
        else
            X = d;
        end
        if exist('X_img','var')
            X_img = [X_img I_img];
        else
            X_img = [I_img];
        end
        y = [y i];
    end
end

numClusters = 10 ;
X = single(X);
[centers, assignments] = vl_kmeans(X, numClusters);

for i = 1:length(X_img)
    raw_img(i).label = X_img(i).label;
    [m,n] = size(X_img(i).descrip)
    for j = 1:n
        [~, k] = min(vl_alldist(X_img(i).descrip(:,j), centers)) ;   
        if exist('hist1','var')
            hist1 = [hist1 k];
        else
            hist1 = [k];
        end
    raw_img(i).hist = hist1;
    end
end    

sift_features = []
y = []
for i = 1:length(raw_img)
    fe(numClusters) = 0; 
    for j = 1:length(raw_img(i).hist)
        fe(raw_img(i).hist(j))= fe(raw_img(i).hist(j)) + 1;
    end
    sift_features = [sift_features ; fe];
    y = [y ; raw_img(i).label];
end

save('feat_sift_vlfeat.mat','sift_features','y')
